Ashfaq-Ahmed-Mohammed/Team-CourtLink

BackEnd/DataBase/DataBase.go, BackEnd/go.mod, BackEnd/go.sum, BackEnd/main.go
Added the backend folder and  Database package in Go Land
=> Added backend folder and Database Package

CourtLink/src/app/app.component.html, CourtLink/src/app/app.component.ts, CourtLink/src/app/components/navbar/navbar.component.html, CourtLink/src/app/components/sports/sports.component.html, CourtLink/src/app/components/sports/sports.component.ts
Added the sports section under the Navbar. It displays some example sports in separate tiles for the user to choose from. Also added some styling to the page and color matched the navbar to the rest of the gradient background.
=> added Sports Component

BackEnd/Court/GetCourts.go, BackEnd/DataBase/DataBase.go, BackEnd/main.go
Added code to search for available courts for the selected court and send it to the frontend
=> Added HTTP GET API to send information on court availability to the FrontEnd

BackEnd/Customer/CreateCustomer.go, BackEnd/DataBase/DataBase.go, BackEnd/go.mod, BackEnd/go.sum, BackEnd/main.go
Added the backend code to support token validation and json from Auth0. Further to this me and @ram-pandeyxx will be working on angular and Go integration to use Auth0 user information to store in the database.
=> Added the backend code to support token validation and json from Auth0

BackEnd/Customer/CreateCustomer.go
Validation added to store records only once. As part of this when a customer is already present in the DB. For every login, his record won't be adde din this table.
=> Validation added to store records only once

BackEnd/Court/GetCourts.go, BackEnd/Court/UpdateCourts.go, BackEnd/DataBase/DataBase.go, BackEnd/main.go
Made changes to the GetCourts API (Optimised) and Added the UpdateCourtSlot API
=> Made changes to the GetCourts API (Optimised) and Added the UpdateCourtSlot API

BackEnd/Bookings/CreateBooking.go, BackEnd/DataBase/DataBase.go, BackEnd/main.go
The capability to have bookings created for the sport, court and customer has been addressed.
=> Bookings POST method is implemented

BackEnd/Bookings/CreateBooking.go, BackEnd/DataBase/DataBase.go, BackEnd/main.go
The Booking capability for the selected sport and court has been achieved as part of this issue.
=> Booking post capability is added

BackEnd/Customer/CreateCustomer_test.go
Added unit test case for createcustomerapi
=> Added unit test case for createcustomerapi

BackEnd/Bookings/CreateBooking_test.go, BackEnd/Customer/CreateCustomer_test.go
Test case added for create booking api
=> Test case added for create booking api

CourtLink/cypress/cypress.config.ts, CourtLink/src/app/app.component.spec.ts, CourtLink/src/app/components/courts/courts.component.spec.ts, CourtLink/src/app/components/navbar/navbar.component.spec.ts, CourtLink/src/app/components/sports/sports.component.spec.ts, CourtLink/src/app/services/api.service.spec.ts, CourtLink/src/polyfills.ts, CourtLink/src/test.ts
Wrote test cases for Navbar component and Courts component
=> Wrote test cases for Navbar component and Courts component

CourtLink/src/app/components/courts/courts.component.html, CourtLink/src/app/components/courts/courts.component.ts
Parsing the JSON from backend and displaying timeslots from Array data
-If the array index has 1 then the time slot will be available, if 0 it will show unavailable
-color coded the buttons
=> Parsing the JSON from backend and displaying timeslots from Array data

CourtLink/src/app/components/courts/courts.component.html, CourtLink/src/app/components/courts/courts.component.ts, CourtLink/src/app/services/api.service.ts
Added the confirm dialogue box, which shows users to make them aware of the booking details before booking the court
Made some CSS changes to it
=> Added the confirm dialogue box

BackEnd/Sport/CreateSport.go
The create sport api has been implemented and tested fully
=> Implemented create sport api fully

CourtLink/src/app/app.component.html, CourtLink/src/app/app.component.ts, CourtLink/src/app/app.routes.ts, CourtLink/src/app/components/admin/admin.component.html, CourtLink/src/app/components/admin/admin.component.spec.ts, CourtLink/src/app/components/admin/admin.component.ts, CourtLink/src/app/components/sports/sports.component.spec.ts, CourtLink/src/app/routes.ts
I have added the admin page. this is how it is looking right now:
=> added the admin page

BackEnd/Sport/ListSports.go, BackEnd/main.go
The API has been added to fetch all list of sports
=> Added List API to fetch all sports

CourtLink/src/app/app.routes.ts, CourtLink/src/app/components/add-sport-dialog/add-sport-dialog.component.html, CourtLink/src/app/components/add-sport-dialog/add-sport-dialog.component.spec.ts, CourtLink/src/app/components/add-sport-dialog/add-sport-dialog.component.ts, CourtLink/src/app/components/admin-sports/admin-sports.component.html, CourtLink/src/app/components/admin-sports/admin-sports.component.spec.ts, CourtLink/src/app/components/admin-sports/admin-sports.component.ts, CourtLink/src/app/components/admin/admin.component.html, CourtLink/src/app/components/admin/admin.component.ts, CourtLink/src/app/routes.ts
As the title suggests, I have created the admin-sports component to view and edit sports. This is what it looks like:
=> added the sports section to display and edit sports

BackEnd/Court/ListCourts.go, BackEnd/main.go
Implemented ListAPI that returns the list of courts and associated sport
=> Implemented ListAPI that returns the list of courts and associated sport

CourtLink/src/main.ts
I have fixed the issue we were running into. Auth0 should now work as expected.
=> fixed issue with auth0

BackEnd/Court/CreateCourt_test.go
Unit test case for create court api
=> Unit test case for create court api

BackEnd/Sport/CreateSport.go, BackEnd/Sport/CreateSport_test.go
Test case for create sport api
=> Test case for create sport api

BackEnd/Court/ListCourts_test.go
Added list courts api test case
=> Added list courts api test case

BackEnd/Sport/ListSports_test.go
added test case for list sports
=> added test case for list sports

BackEnd/Court/DeleteCourt_test.go
Added test case for delete court api
=> Added test case for delete court api

CourtLink/src/app/components/admin/admin.component.spec.ts
I ran some unit tests on the admin component and am attaching a screenshot of the results here:
=> performed unit testing for admin component

CourtLink/package-lock.json, CourtLink/package.json, CourtLink/src/app/components/navbar/navbar.component.spec.ts, CourtLink/tsconfig.spec.json
Performed Unit Testingon Navbar component Sprint 3
=> Performed Unit Testingon Navbar component Sprint 3

CourtLink/src/app/components/courts/courts.component.spec.ts, CourtLink/src/app/components/courts/courts.component.ts
Performed Unit Testing on Courts Component
=> Performed Unit Testing on Courts Component

CourtLink/src/app/components/my-bookings/my-bookings.component.spec.ts
Performed Unit Tests on My-Bookings component
=> Performed Unit Tests on My-Bookings component

CourtLink/src/app/app.config.ts, CourtLink/src/app/components/navbar/navbar.component.html, CourtLink/src/app/components/navbar/navbar.component.ts
Added a hmaburger icon with logout and contact us option
Contact us will write an email to "contact@ufcourtlink.com"
=> Added a hmaburger icon with logout and contact us option

BackEnd/Court/ListCourts_test.go
Added more testcases for the listcourts and listbookings APIs
=> Added more testcases for the listcourts and listbookings APIs

CourtLink/cypress/cypress.config.ts, CourtLink/cypress/e2e/home.cy.ts, CourtLink/cypress/support/commands.ts, CourtLink/src/app/components/navbar/navbar.component.spec.ts, CourtLink/src/app/components/sports/sports.component.spec.ts, CourtLink/src/app/components/sports/sports.component.ts
Unit testing on navbar and sports components for new functionality and end to end cypress testing done
=> Unit testing on navbar and sports components for new functionality and end to end cypress testing done

BackEnd/Admin/AdminLogin.go, BackEnd/docs/docs.go, BackEnd/docs/swagger.json, BackEnd/docs/swagger.yaml
Added swagger doc for Admin Login API
=> Added swagger doc for Admin Login API

BackEnd/Court/UpdateCourts.go, BackEnd/Utils/ResetSlots.go, BackEnd/main.go
Added functionality to reset slots on court name
=> Added functionality to reset slots on court name

CourtLink/src/app/app.routes.ts, CourtLink/src/app/components/admin-login/admin-login.component.html, CourtLink/src/app/components/admin-login/admin-login.component.spec.ts, CourtLink/src/app/components/admin-login/admin-login.component.ts
I have added protection for the admin portal in the form of a username and password.
=> added login for admin

BackEnd/Admin/AdminLogin_test.go, BackEnd/Court/UpdateCourts_test.go, BackEnd/Customer/CreateCustomer_test.go, BackEnd/Sport/ListSports_test.go
Added the test cases for new AdminLogin API and added more test cases for list sports and create customer APIs.
=> Added the test cases for new AdminLogin API and added more test cases for list sports and create customer

CourtLink/src/app/components/admin-login/admin-login.component.spec.ts
I have finished unit testing the admin-login component. The tests I ran are:
1. It should create the component.
2. It should navigate to /admin-portal on successful login.
3. It should display an error message when incorrect login credentials are used.
=> unit tested the admin-login component
